name: Node.js Core Test

on:
  push:
    branches:
      - main # Run tests only on pushes to the main branch
  pull_request:
    branches:
      - main # Run tests for pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm test
